# -*- coding: utf-8 -*-
"""har intenship.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PAEBRNkeg1arl3RcRX0b8yqgY-6EoAOh

# Data Cleaning & Visualization Project
"""



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully!")



# Example: Loading a CSV file
# df = pd.read_csv('your_dataset.csv')

# Placeholder for your data loading code
# For demonstration, let's create a dummy DataFrame
data = {
    'FeatureA': [10, 20, np.nan, 40, 50, 100, 10, 25, 30, 45],
    'FeatureB': ['A', 'B', 'A', 'C', 'B', 'A', 'D', 'C', 'B', 'A'],
    'NumericalValue': [1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 10.0],
    'Date': pd.to_datetime(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08', '2023-01-09', '2023-01-10'])
}
df = pd.DataFrame(data)


print("Dataset loaded. Displaying the first 5 rows:")
display(df.head())

"""## 2. Initial Data Exploration

Before cleaning, let's explore the dataset to understand its basic characteristics, identify missing values, and get a statistical summary.
"""

print("### Dataset Information (Data Types, Non-Null Counts): ###")
df.info()

print("\n### Missing Values: ###")
display(df.isnull().sum())

print("\n### Descriptive Statistics for Numerical Columns: ###")
display(df.describe())

print("\n### Check for Duplicate Rows: ###")
print(f"Number of duplicate rows: {df.duplicated().sum()}")

print("\n### Unique Values and Counts for Categorical Columns: ###")
for column in df.select_dtypes(include='object').columns:
    print(f"\nUnique values in '{column}':")
    print(df[column].value_counts())

print("Original DataFrame with missing values:")
display(df)

# Fill missing values in 'FeatureA' with its mean
df['FeatureA'] = df['FeatureA'].fillna(df['FeatureA'].mean())

print("\nDataFrame after filling missing values in 'FeatureA':")
display(df)

print("\nMissing values after imputation:")
display(df.isnull().sum())

initial_rows = df.shape[0]
df.drop_duplicates(inplace=True)
duplicates_removed = initial_rows - df.shape[0]

if duplicates_removed > 0:
    print(f"Removed {duplicates_removed} duplicate rows.")
else:
    print("No duplicate rows found or removed.")

print("\nDataFrame after removing duplicates (if any):")
display(df.head())

plt.figure(figsize=(12, 5))
sns.boxplot(data=df[['FeatureA', 'NumericalValue']])
plt.title('Box Plot of Numerical Features')
plt.ylabel('Value')
plt.show()

plt.figure(figsize=(8, 4))
sns.countplot(x='FeatureB', data=df, palette='viridis')
plt.title('Count of Categories in FeatureB')
plt.xlabel('Category')
plt.ylabel('Count')
plt.show()



"""### Exploring Relationships and Trends"""

print("### Correlation Matrix for Numerical Features: ###")
correlation_matrix = df[['FeatureA', 'NumericalValue']].corr()
plt.figure(figsize=(6, 5))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Numerical Features')
plt.show()

print("### Time Series Plot of NumericalValue: ###")
plt.figure(figsize=(12, 6))
sns.lineplot(x='Date', y='NumericalValue', data=df)
plt.title('NumericalValue Over Time')
plt.xlabel('Date')
plt.ylabel('NumericalValue')
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

print("### Bar Plot of NumericalValue by FeatureB: ###")
plt.figure(figsize=(10, 6))
sns.barplot(x='FeatureB', y='NumericalValue', data=df, palette='pastel')
plt.title('Average NumericalValue by FeatureB Category')
plt.xlabel('FeatureB Category')
plt.ylabel('Average NumericalValue')
plt.show()

print("### Box plot to visualize outliers for 'FeatureA' and 'NumericalValue': ###")
plt.figure(figsize=(10, 6))
sns.boxplot(data=df[['FeatureA', 'NumericalValue']])
plt.title('Box Plot of Numerical Features for Outlier Detection')
plt.ylabel('Value')
plt.show()

# Calculate IQR for 'FeatureA'
Q1 = df['FeatureA'].quantile(0.25)
Q3 = df['FeatureA'].quantile(0.75)
IQR = Q3 - Q1

# Define outlier bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print(f"IQR for FeatureA: {IQR}")
print(f"Lower bound for FeatureA: {lower_bound}")
print(f"Upper bound for FeatureA: {upper_bound}")

# Identify and cap outliers
df['FeatureA_cleaned'] = df['FeatureA'].copy()
df.loc[df['FeatureA_cleaned'] < lower_bound, 'FeatureA_cleaned'] = lower_bound
df.loc[df['FeatureA_cleaned'] > upper_bound, 'FeatureA_cleaned'] = upper_bound

print("\nDataFrame after capping outliers in 'FeatureA':")
display(df[['FeatureA', 'FeatureA_cleaned']].head(10))

# Visualize 'FeatureA' after outlier capping
plt.figure(figsize=(10, 6))
sns.boxplot(data=df[['FeatureA', 'FeatureA_cleaned']])
plt.title('Box Plot of FeatureA Before and After Outlier Capping')
plt.ylabel('Value')
plt.show()